const actions = {
  CHEAP_REQUEST: 'CHEAP_REQUEST',
  CHEAP_SUCCESS: 'CHEAP_SUCCESS',
  CHEAP_LOADING: 'CHEAP_LOADING',
  CHEAP_ERROR: 'CHEAP_ERROR',

  BUSINESS_REQUEST: 'BUSINESS_REQUEST',
  BUSINESS_SUCCESS: 'BUSINESS_SUCCESS',
  BUSINESS_LOADING: 'BUSINESS_LOADING',
  BUSINESS_ERROR: 'BUSINESS_ERROR',

  CREATE_FLIGHT_REQUEST: 'CREATE_FLIGHT_REQUEST',
  CREATE_FLIGHT_SUCCESS: 'CREATE_FLIGHT_SUCCESS',
  CREATE_FLIGHT_LOADING: 'CREATE_FLIGHT_LOADING',
  CREATE_FLIGHT_ERROR: 'CREATE_FLIGHT_ERROR',

  FLIGHT_RESET: 'FLIGHT_RESET',

  getCheap: () => ({
    type: actions.CHEAP_REQUEST
  }),
  getBusiness: () => ({
    type: actions.BUSINESS_REQUEST
  }),
  addFlight: params => ({
    type: actions.CREATE_FLIGHT_REQUEST,
    params
  })
};
export default actions;
